#:schema https://conductor.build/schemas/settings.repo.schema.json

[scripts]
setup = "dart pub upgrade --no-precompile"
archive = "true"
run_mode = "concurrent"

[scripts.run.vm-tests]
command = "dart test --platform vm"
default = true
icon = "test-tube"

[scripts.run.chrome-tests]
command = "dart test --platform chrome"
icon = "globe"

[scripts.run.analyze]
command = "dart analyze --fatal-infos ."
icon = "braces"

[scripts.run.format-check]
command = "dart format --output=none --set-exit-if-changed ."
icon = "braces"

[scripts.run.example]
command = "dart run --enable-asserts example/simple.dart"
icon = "play"
